export default {
  legos: [
    {
      legoId: '1',
      Legoname: 'Chrome Gold Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/chromeGold.png',
      price: 37,
      stock: 25,
      cart: 0,
    },
    {
      legoId: '2',
      Legoname: 'Pink Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/pink.png',
      price: 24,
      stock: 70,
      cart: 0,
    },
    {
      legoId: '3',
      Legoname: 'Green Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/green.png',
      price: 18,
      stock: 50,
      cart: 0,
    },
    {
      legoId: '4',
      Legoname: 'Orange Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/orange.png',
      price: 21,
      stock: 50,
      cart: 0,
    },
    {
      legoId: '5',
      Legoname: 'Purple Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/purple.png',
      price: 16,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '6',
      Legoname: 'Reddish Lilac Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/reddishLilac.png',
      price: 28,
      stock: 50,
      cart: 0,
    },
    {
      legoId: '7',
      Legoname: 'Brown Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/brown.png',
      price: 55,
      stock: 60,
      cart: 0,
    },
    {
      legoId: '8',
      Legoname: 'Yellow Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/yellow.png',
      price: 0.98,
      stock: 135,
      cart: 0,
    },
    {
      legoId: '9',
      Legoname: 'Blue Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/blue.png',
      price: 17,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '10',
      Legoname: 'Aqua Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/aqua.png',
      price: 23,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '11',
      Legoname: 'Red Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/red.png',
      price: 19,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '12',
      Legoname: 'White Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/white.png',
      price: 15,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '13',
      Legoname: 'Soldier',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/greenkit.png',
      price: 240,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '14',
      Legoname: 'Soldier\'s Armour',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/greenChest.png',
      price: 100,
      stock: 88,
      cart: 0,
    },
    {
      legoId: '15',
      Legoname: 'Left Arm',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/greenLeftArm.png',
      price: 0.99,
      stock: 100,
      cart: 0,
    },
    {
      legoId: '16',
      Legoname: 'Right Arm',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/greenRightArm.png',
      price: 0.99,
      stock: 100,
      cart: 0,
    },
    {
      legoId: '17',
      Legoname: 'Hand',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/greenHand.png',
      price: 10,
      stock: 80,
      cart: 0,
    },
    {
      legoId: '18',
      Legoname: 'Bike',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/yellowBike.png',
      price: 60,
      stock: 38,
      cart: 0,
    },
    {
      legoId: '19',
      Legoname: 'Bike\'s Body',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/bikeBrick.png',
      price: 30,
      stock: 35,
      cart: 0,
    },
    {
      legoId: '20',
      Legoname: 'Tire',
      category: 'Bricks',
      categoryId: 3,
      image: 'images/usedInventories/tire.png',
      price: 20,
      stock: 47,
      cart: 0,
    },
  ],
};
