export default {
  legos: [
    {
      legoId: '1',
      name: 'Chrome Gold Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/chromeGold.png',
      price: 37,
      stockLevels: 25,
    },
    {
      legoId: '2',
      name: 'Pink Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/pink.png',
      price: 24,
      stockLevels: 70,
    },
    {
      legoId: '3',
      name: 'Green Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/green.png',
      price: 18,
      stockLevels: 50,
    },
    {
      legoId: '4',
      name: 'Orange Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/orange.png',
      price: 21,
      stockLevels: 50,
    },
    {
      legoId: '5',
      name: 'Purple Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/purple.png',
      price: 16,
      stockLevels: 88,
    },
    {
      legoId: '6',
      name: 'Reddish Lilac Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/reddishLilac.png',
      price: 28,
      stockLevels: 50,
    },
    {
      legoId: '7',
      name: 'Brown Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/brown.png',
      price: 55,
      stockLevels: 60,
    },
    {
      legoId: '8',
      name: 'Yellow Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/yellow.png',
      price: 0.98,
      stockLevels: 135,
    },
    {
      legoId: '9',
      name: 'Blue Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/blue.png',
      price: 17,
      stockLevels: 88,
    },
    {
      legoId: '10',
      name: 'Aqua Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/aqua.png',
      price: 23,
      stockLevels: 88,
    },
    {
      legoId: '11',
      name: 'Red Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/red.png',
      price: 19,
      stockLevels: 88,
    },
    {
      legoId: '12',
      name: 'White Brick',
      category: 'Bricks',
      categoryId: 2,
      image: 'images/usedInventories/white.png',
      price: 15,
      stockLevels: 88,
    },
    {
      legoId: '13',
      name: 'Soldier',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/greenkit.png',
      price: 240,
      stockLevels: 88,
    },
    {
      legoId: '14',
      name: 'Soldier\'s Armour',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/greenChest.png',
      price: 100,
      stockLevels: 88,
    },
    {
      legoId: '15',
      name: 'Left Arm',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/greenLeftArm.png',
      price: 0.99,
      stockLevels: 100,
    },
    {
      legoId: '16',
      name: 'Right Arm',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/greenRightArm.png',
      price: 0.99,
      stockLevels: 100,
    },
    {
      legoId: '17',
      name: 'Hand',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/greenHand.png',
      price: 10,
      stockLevels: 80,
    },
    {
      legoId: '18',
      name: 'Bike',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/yellowBike.png',
      price: 60,
      stockLevels: 38,
    },
    {
      legoId: '19',
      name: 'Bike\'s Body',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/bikeBrick.png',
      price: 30,
      stockLevels: 35,
    },
    {
      legoId: '20',
      name: 'Tire',
      category: 'Kits',
      categoryId: 3,
      image: 'images/usedInventories/tire.png',
      price: 20,
      stockLevels: 47,
    },
  ],
};
