export default {
  legos: [
    {
      kitId: '1',
      name: 'Peaky Blinders',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/peakyBlinders.png',
      price: 500,
      stock: 88,
      cart: 0,
    },
    {
      kitId: '2',
      name: 'Micheal Scofield',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/scofield.png',
      price: 399,
      stock: 50,
      cart: 0,
    },
    {
      kitId: '3',
      name: 'Joker',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/joker.png',
      price: 364,
      stock: 33,
      cart: 0,
    },
    {
      kitId: '4',
      name: 'Tasmanian Devil',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/TasmanianDevil.png',
      price: 260,
      stock: 39,
      cart: 0,
    },
    {
      kitId: '5',
      name: 'Viking',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/viking.png',
      price: 160,
      stock: 98,
      cart: 0,
    },
    {
      kitId: '6',
      name: 'Lambo',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/lambo.png',
      price: 370,
      stock: 25,
      cart: 0,
    },
    {
      kitId: '7',
      name: 'Colosseum',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/colosseum.png',
      price: 300,
      stock: 70,
      cart: 0,
    },
    {
      kitId: '8',
      name: 'Hogwarts',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/hogwarts.png',
      price: 320,
      stock: 50,
      cart: 0,
    },
    {
      kitId: '9',
      name: 'New York',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/newYork.png',
      price: 240,
      stock: 50,
      cart: 0,
    },
    {
      kitId: '10',
      name: 'Taj Mahal',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/tajMahal.png',
      price: 392,
      stock: 10,
      cart: 0,
    },

    {
      kitId: '11',
      name: 'Skyhawk',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/Skyhawk.png',
      price: 259,
      stock: 19,
      cart: 0,
    },

    {
      kitId: '12',
      name: 'F1 Lotus E20',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/F1LotusE20.png',
      price: 499,
      stock: 38,
      cart: 0,
    },
    {
      kitId: '13',
      name: 'Madrid\'s Stadium',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/madrid.png',
      price: 1000,
      stock: 20,
      cart: 0,
    },
    {
      kitId: '14',
      name: 'Iron Man Helmet',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/ironManHelmet.png',
      price: 200,
      stock: 76,
      cart: 0,
    },
    {
      kitId: '15',
      name: 'Captain America',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/captainA.png',
      price: 400,
      stock: 32,
      cart: 0,
    },
    {
      kitId: '16',
      name: 'Iron Man',
      category: 'Kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/ironMan.png',
      price: 374,
      stock: 81,
      cart: 0,
    },
  ],
};
