export default {
  legos: [
    {
      kitId: '1',
      name: 'Lambo',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/lambo.png',
      price: 37,
      stockLevels: 25,
    },
    {
      kitId: '2',
      name: 'Colosseum',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/colosseum.png',
      price: 24,
      stockLevels: 70,
    },
    {
      kitId: '3',
      name: 'Hogwarts',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/hogwarts.png',
      price: 18,
      stockLevels: 50,
    },
    {
      kitId: '4',
      name: 'New York',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/newYork.png',
      price: 21,
      stockLevels: 50,
    },
    {
      kitId: '5',
      name: 'Taj Mahal',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/tajMahal.png',
      price: 16,
      stockLevels: 88,
    },
  ],
};
