export default {
  legos: [
    {
      kitId: '1',
      name: 'Peaky Blinders',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/peakyBlinders.png',
      price: 500,
      stockLevels: 88,
    },
    {
      kitId: '2',
      name: 'Micheal Scofield',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/scofield.png',
      price: 399,
      stockLevels: 88,
    },
    {
      kitId: '3',
      name: 'Joker',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/joker.png',
      price: 364,
      stockLevels: 88,
    },
    {
      kitId: '4',
      name: 'Tasmanian Devil',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/TasmanianDevil.png',
      price: 260,
      stockLevels: 88,
    },
    {
      kitId: '5',
      name: 'viking',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/viking.png',
      price: 160,
      stockLevels: 88,
    },
    {
      kitId: '6',
      name: 'Lambo',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/lambo.png',
      price: 370,
      stockLevels: 25,
    },
    {
      kitId: '7',
      name: 'Colosseum',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/colosseum.png',
      price: 300,
      stockLevels: 70,
    },
    {
      kitId: '8',
      name: 'Hogwarts',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/hogwarts.png',
      price: 320,
      stockLevels: 50,
    },
    {
      kitId: '9',
      name: 'New York',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/newYork.png',
      price: 240,
      stockLevels: 50,
    },
    {
      kitId: '10',
      name: 'Taj Mahal',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/tajMahal.png',
      price: 392,
      stockLevels: 88,
    },

    {
      kitId: '11',
      name: 'Skyhawk',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/Skyhawk.png',
      price: 259,
      stockLevels: 88,
    },

    {
      kitId: '12',
      name: 'F1 Lotus E20',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/F1LotusE20.png',
      price: 499,
      stockLevels: 88,
    },
    {
      kitId: '13',
      name: 'Madrid\'s Stadium',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/madrid.png',
      price: 1000,
      stockLevels: 88,
    },
    {
      kitId: '14',
      name: 'Iron Man Helmet',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/ironManHelmet.png',
      price: 200,
      stockLevels: 88,
    },
    {
      kitId: '15',
      name: 'Captain America',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/captainA.png',
      price: 400,
      stockLevels: 88,
    },
    {
      kitId: '16',
      name: 'Iron Man',
      category: 'kits',
      categoryId: 2,
      image: 'images/usedInventories/kits/ironMan.png',
      price: 374,
      stockLevels: 88,
    },

  ],
};
